/** Static defaults used when DB has no Active items — keeps homepage unchanged until admin manages content. */

export const DEFAULT_CLIENT_LOGOS = Array.from({ length: 36 }, (_, i) => ({
  id: `default-client-${i + 1}`,
  name: `Client ${i + 1}`,
  logoUrl: `/clients/${i + 1}.jpg`,
  sortOrder: i + 1,
  status: 'Active',
}))

export const DEFAULT_AFFILIATIONS = [
  { id: 'default-aff-1', name: 'Accreditation Partner 1', imageUrl: '/Affiliations/1.png', url: '#', sortOrder: 1 },
  { id: 'default-aff-2', name: 'Accreditation Partner 2', imageUrl: '/Affiliations/2.png', url: '#', sortOrder: 2 },
  { id: 'default-aff-3', name: 'Accreditation Partner 3', imageUrl: '/Affiliations/3.png', url: '#', sortOrder: 3 },
  { id: 'default-aff-4', name: 'Accreditation Partner 4', imageUrl: '/Affiliations/4.png', url: '/courses/certificate/696e0459612d640dea16b6ba', sortOrder: 4 },
  { id: 'default-aff-5', name: 'Accreditation Partner 5', imageUrl: '/Affiliations/5.png', url: '#', sortOrder: 5 },
  { id: 'default-aff-6', name: 'Accreditation Partner 6', imageUrl: '/Affiliations/1.jpg', url: '#', sortOrder: 6 },
  { id: 'default-aff-7', name: 'Accreditation Partner 7', imageUrl: '/Affiliations/2.jpg', url: '#', sortOrder: 7 },
  { id: 'default-aff-8', name: 'Accreditation Partner 8', imageUrl: '/Affiliations/3.jpg', url: '#', sortOrder: 8 },
  { id: 'default-aff-9', name: 'Accreditation Partner 9', imageUrl: '/Affiliations/4.jpg', url: '#', sortOrder: 9 },
  { id: 'default-aff-10', name: 'Accreditation Partner 10', imageUrl: '/Affiliations/5.jpg', url: '#', sortOrder: 10 },
  { id: 'default-aff-11', name: 'Accreditation Partner 11', imageUrl: '/Affiliations/6.jpg', url: '#', sortOrder: 11 },
  { id: 'default-aff-12', name: 'Accreditation Partner 12', imageUrl: '/Affiliations/7.jpg', url: '#', sortOrder: 12 },
  { id: 'default-aff-13', name: 'Accreditation Partner 13', imageUrl: '/Affiliations/8.jpg', url: '#', sortOrder: 13 },
  { id: 'default-aff-14', name: 'Accreditation Partner 14', imageUrl: '/Affiliations/9.jpg', url: '#', sortOrder: 14 },
  { id: 'default-aff-15', name: 'Accreditation Partner 15', imageUrl: '/Affiliations/10.jpg', url: '/courses/certificate/696e060364e06418a46a3a4f', sortOrder: 15 },
  { id: 'default-aff-16', name: 'Accreditation Partner 16', imageUrl: '/Affiliations/11.jpg', url: '#', sortOrder: 16 },
  { id: 'default-aff-17', name: 'Accreditation Partner 17', imageUrl: '/Affiliations/12.jpg', url: '/courses/certificate/696e06f264e06418a46a3a50', sortOrder: 17 },
  { id: 'default-aff-18', name: 'Accreditation Partner 18', imageUrl: '/Affiliations/13.jpg', url: '#', sortOrder: 18 },
].map((a) => ({ ...a, status: 'Active' }))

export const DEFAULT_TESTIMONIALS = [
  {
    id: 'default-t-1',
    course: 'Project Management Masterclass',
    rating: 5,
    review:
      'One of the most beneficial course attended this year. Instructors capabilities to keep attention is excellent and he presented subjects clearly with great examples.',
    name: 'Umar Bakoji',
    position: 'Manager Services',
    company: 'Qatar Financial Authority',
    avatarUrl: '/placeholder.svg?height=60&width=60',
    verified: true,
    sortOrder: 1,
    status: 'Active',
  },
  {
    id: 'default-t-2',
    course: 'Putting Strategy into Action',
    rating: 5,
    review:
      'This program was excellent. Very practical, nice facilities and a great instructor who understood our business',
    name: 'Maryrose R O',
    position: 'General Manager',
    company: null,
    avatarUrl: '/placeholder.svg?height=60&width=60',
    verified: true,
    sortOrder: 2,
    status: 'Active',
  },
  {
    id: 'default-t-3',
    course: 'Leadership for 4IR: the 4.0D Leadership Model',
    rating: 5,
    review:
      'I have attended more than 30 training programs in my career and this was by far the best Leadership training event EVER! Johann and John are a compelling double act.',
    name: 'Dr. James D. Wilson.',
    position: 'BDS',
    company: null,
    avatarUrl: '/placeholder.svg?height=60&width=60',
    verified: true,
    sortOrder: 3,
    status: 'Active',
  },
  {
    id: 'default-t-4',
    course: 'Due Diligence in the Petroleum Business',
    rating: 5,
    review:
      'The instructor made the complexities of corporate governance seem easy. Thoroughly recommend this program.',
    name: 'Yakubu A',
    position: 'General Manager',
    company: null,
    avatarUrl: '/placeholder.svg?height=60&width=60',
    verified: true,
    sortOrder: 4,
    status: 'Active',
  },
  {
    id: 'default-t-5',
    course: 'Key Managerial Skills for New Managers & Supervisors',
    rating: 5,
    review:
      'A good mix of theory and practice I feel much more confident now in my new role as Shift Supervisor.',
    name: 'Rachel N',
    position: 'Office Procurement',
    company: null,
    avatarUrl: '/placeholder.svg?height=60&width=60',
    verified: true,
    sortOrder: 5,
    status: 'Active',
  },
  {
    id: 'default-t-6',
    course: 'Procurement & Supply Chain Management',
    rating: 5,
    review: 'This was an intensive program over 10 days, but the time flew by, thank you.',
    name: 'Imi Umaru',
    position: 'Manager Procurement',
    company: null,
    avatarUrl: '/placeholder.svg?height=60&width=60',
    verified: true,
    sortOrder: 6,
    status: 'Active',
  },
  {
    id: 'default-t-7',
    course: 'Financial Statement Analysis of the Public Sector',
    rating: 5,
    review: 'Excellent course 5* Great instructors who knew their subject matter well.',
    name: 'Abdullah Al Thani',
    position: 'Senior Financial Analyst',
    company: null,
    avatarUrl: '/placeholder.svg?height=60&width=60',
    verified: true,
    sortOrder: 7,
    status: 'Active',
  },
  {
    id: 'default-t-8',
    course: "Developing Professional Skills for Executive Secretaries & PA's",
    rating: 5,
    review: 'The trainer was excellent, she helped everyone and provided excellent examples',
    name: 'Moza Al Ali',
    position: 'PA - Group Chairman',
    company: null,
    avatarUrl: '/placeholder.svg?height=60&width=60',
    verified: true,
    sortOrder: 8,
    status: 'Active',
  },
  {
    id: 'default-t-9',
    course: 'Pumps & Compressors: Operation, Maintenance & Troubleshooting',
    rating: 5,
    review: 'High level training delivered by High level instructors',
    name: 'Mohammed Al Abdallah',
    position: 'Maintenance Engineer',
    company: null,
    avatarUrl: '/placeholder.svg?height=60&width=60',
    verified: true,
    sortOrder: 9,
    status: 'Active',
  },
]
